
server :
  port : 8000
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 2GB
  devtools:
    livereload:
      enabled: true
    datasource:
      url: jdbc:mysql://localhost:3306/files?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
  
  ## File Storage Properties
  # All files uploaded through the REST API will be stored in this directory
  
  ## ?????? ??? ??? ??? ???? ??? 16?? ??? 
  ## ?? PC? ?? dir? ??? ?? ??? 17?? ??? ????. 
  #file.upload-dir=./uploads 
  # file.upload-dir=F:\posco\test\UPLOAD_FILES
file:
  upload-dir: /uploads